### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [useragents/Discord-Token-Checker#2]
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'line-reader'
Require stack:
- C:\Users\wokedos\Desktop\Discord-Token-Checker-main\token_checker.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> (C:\Users\wokedos\Desktop\Discord-Token-Checker-main\token_checker.js:1:20)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1105:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\wokedos\\Desktop\\Discord-Token-Checker-main\\token_checker.js'←[39m
  ]
}

**Comment by useragents** [comment]
Not an issue with my script, type the following into Command Prompt:
```
npm i line-reader
npm i xmlhttprequest
```
